const styles = {
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.3)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  modal: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 24,
    width: 400,
    boxShadow: "0 4px 12px rgba(0,0,0,0.15)",
    display: "flex",
    flexDirection: "column",
  },
  title: {
    marginBottom: 16,
    fontWeight: 700,
    fontSize: 22,
    color: "#0f1419",
  },
  textarea: {
    resize: "none",
    borderRadius: 12,
    border: "1px solid #e1e8ed",
    padding: 12,
    fontSize: 16,
    color: "#0f1419",
    marginBottom: 20,
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
  },
  buttons: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 12,
  },
  saveBtn: {
    backgroundColor: "#1d9bf0",
    border: "none",
    color: "white",
    padding: "10px 18px",
    borderRadius: 9999,
    fontWeight: 600,
    fontSize: 15,
    cursor: "pointer",
    transition: "background-color 0.2s ease",
    boxShadow: "0 1px 3px rgb(0 0 0 / 0.2)",
  },
  saveBtnHover: {
    backgroundColor: "#1a8cd8",
  },
  saveBtnDisabled: {
    backgroundColor: "#a4d9f9",
    color: "white",
    cursor: "not-allowed",
    opacity: 0.6,
    boxShadow: "none",
  },
  cancelBtn: {
    backgroundColor: "transparent",
    border: "none",
    color: "#1d9bf0",
    fontWeight: 600,
    fontSize: 15,
    cursor: "pointer",
    padding: "10px 18px",
    borderRadius: 9999,
    transition: "background-color 0.2s ease",
  },
  cancelBtnHover: {
    backgroundColor: "#e8f5fd",
  },
};

export default styles;
